backend: auto
data:
  scripts_file: data/sample_scripts.txt
diffusion:
  base_model: runwayml/stable-diffusion-v1-5
  dtype: fp16
  guidance_scale: 7.5
  height: 512
  num_inference_steps: 30
  seed: 42
  width: 512
generation:
  fps: 24
  frames_dir: outputs/frames
  num_scenes: 5
  output_dir: outputs
  output_video: outputs/sample_output.mp4
