# Speed-optimized config
model: "runwayml/stable-diffusion-v1-5"
steps: 8          # Reduced from 20
guidance: 6.0     # Reduced from 7.5  
size: [384, 512]  # Smaller than [512, 768]
shots: 3          # Reduced from 5
script: "script.txt"
