
backend: "auto" 

# Diffusion model settings
diffusion:
  base_model: "runwayml/stable-diffusion-v1-5"
  guidance_scale: 7.5
  num_inference_steps: 30
  height: 512
  width: 512
  seed: 42
  dtype: "fp16"

# Generation settings
generation:
  fps: 24
  output_dir: "outputs"
  frames_dir: "outputs/frames"
  output_video: "outputs/sample_output.mp4"
  num_scenes: 5

# Data paths
data:
  scripts_file: "data/sample_scripts.txt"